In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
#creating a numpy array
#numpy.array(object,dtype=None,copy=True,order=None,subok=False,ndim=0)
#object=list,tuple,dict,set
#dtype=float, int,etc, default is none
#copy=option object is copied default is true
#order=col,row,any
#subok= array witll be base classes
#ndim= minimum dimension

a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [15]:
a=np.array([[1,2,3],[4,5,6]],dtype='complex')
a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [19]:
print(a.ndim) #no of dimensions
print(a.itemsize) #size of each value
print(a.dtype) #data type of each value
print(a.shape) #shape of array
print(a.size) #size of array - total elements

2
16
complex128
(2, 3)
6


In [23]:
#reshaping array objects
#changing the rows and columns
#reshape function in ndarray allows us to do so
print(a.shape) #current shape
a=a.reshape((3,2))
print(a.shape) #changed shape

(2, 3)
(3, 2)


In [29]:
#array slicing 
#it is similar to list slicing
#used to access values between indices
a=np.arange(1,51).reshape(5,10)
print(a) #our array
print(a[0,1]) #accessing value as 0th row and 1st column
print(a[1:3,4:6]) #accessing value as between 1st and 3rd (Exluded) rows and 4th and 6th(Excluded) columns

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
2
[[15 16]
 [25 26]]


In [30]:
#linspace function in numpy
#this function returns an array with evenly space values in a given interval
a=np.linspace(5,15,10) #start is 5 , end is 15 and diff 1is 10
print(a)

[ 5.          6.11111111  7.22222222  8.33333333  9.44444444 10.55555556
 11.66666667 12.77777778 13.88888889 15.        ]


In [33]:
#min, max in numpy array
print(a.min()) #get minimum value in an array
print(a.max())  #get max value in an array
print(a.sum())  #get sum of array elements

5.0
15.0
100.0


In [40]:
#square root and standar deviation in numpy array
print(np.sqrt(a)) #to get the square root 
print(np.std(a)) #to get standard deviation

[2.23606798 2.47206616 2.68741925 2.88675135 3.07318149 3.24893145
 3.41565026 3.57460176 3.72677996 3.87298335]
3.191423692521127


In [49]:
#arthimetic operation on arrays
a=np.arange(1,21).reshape(4,5)
b=np.arange(21,41).reshape(4,5)
print(a+b) #sum of arrays
print(a-b) #differnce of arrays
print(a/b) #division of arrays

[[22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]]
[[-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]]
[[0.04761905 0.09090909 0.13043478 0.16666667 0.2       ]
 [0.23076923 0.25925926 0.28571429 0.31034483 0.33333333]
 [0.35483871 0.375      0.39393939 0.41176471 0.42857143]
 [0.44444444 0.45945946 0.47368421 0.48717949 0.5       ]]


In [53]:
#array concatenation in numpy
#can be done by using hstack and vstack
print(np.hstack((a,b))) #horizontal concatenation of array
print(np.vstack((a,b))) #vertical concatenation of array

[[ 1  2  3  4  5 21 22 23 24 25]
 [ 6  7  8  9 10 26 27 28 29 30]
 [11 12 13 14 15 31 32 33 34 35]
 [16 17 18 19 20 36 37 38 39 40]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [ ]:
#data types in numpy library